=== DLawls/trading-platform/financial_data_collector/yahoo_finance_collector/schema/ohlcv.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "OHLCV Data",
  "type": "object",
  "properties": {
    "ticker": {"type": "string"},
    "datetime": {"type": "string", "format": "date-time"},
    "open": {"type": "number"},
    "high": {"type": "number"},
    "low": {"type": "number"},
    "close": {"type": "number"},
    "volume": {"type": "number"}
  },
  "required": ["ticker", "datetime", "open", "high", "low", "close", "volume"]
}

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_ETHUSD_daily_ohlcv_20250727.json
[
  {
    "ticker": "ETHUSD",
    "datetime": "2025-06-27T09:49:06",
    "open": 64.82,
    "high": 65.86,
    "low": 64.58,
    "close": 64.84,
    "volume": 2654604
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-06-28T09:49:06",
    "open": 65.53,
    "high": 65.75,
    "low": 65.11,
    "close": 65.66,
    "volume": 2363980
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-06-29T09:49:06",
    "open": 65.29,
    "high": 66.56,
    "low": 64.37,
    "close": 65.55,
    "volume": 836357
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-06-30T09:49:06",
    "open": 68.41,
    "high": 68.91,
    "low": 67.42,
    "close": 68.71,
    "volume": 5715548
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-01T09:49:06",
    "open": 68.02,
    "high": 69.2,
    "low": 67.64,
    "close": 67.78,
    "volume": 4888234
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-02T09:49:06",
    "open": 67.43,
    "high": 69.13,
    "low": 67.07,
    "close": 67.81,
    "volume": 7647755
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-03T09:49:06",
    "open": 66.66,
    "high": 67.99,
    "low": 65.79,
    "close": 66.32,
    "volume": 8327709
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-04T09:49:06",
    "open": 64.46,
    "high": 65.61,
    "low": 63.24,
    "close": 64.31,
    "volume": 7569117
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-05T09:49:06",
    "open": 63.61,
    "high": 64.07,
    "low": 62.52,
    "close": 63.83,
    "volume": 9224108
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-06T09:49:06",
    "open": 63.74,
    "high": 65.01,
    "low": 63.11,
    "close": 63.92,
    "volume": 5186494
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-07T09:49:06",
    "open": 62.31,
    "high": 63.11,
    "low": 61.89,
    "close": 62.02,
    "volume": 8760061
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-08T09:49:06",
    "open": 62.14,
    "high": 63.23,
    "low": 60.7,
    "close": 61.63,
    "volume": 2399811
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-09T09:49:06",
    "open": 63.22,
    "high": 63.91,
    "low": 63.08,
    "close": 63.11,
    "volume": 3776570
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-10T09:49:06",
    "open": 63.74,
    "high": 64.9,
    "low": 63.73,
    "close": 63.88,
    "volume": 1928086
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-11T09:49:06",
    "open": 66.39,
    "high": 66.85,
    "low": 66.14,
    "close": 66.52,
    "volume": 9088228
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-12T09:49:06",
    "open": 64.99,
    "high": 65.93,
    "low": 64.57,
    "close": 64.94,
    "volume": 2023495
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-13T09:49:06",
    "open": 67.65,
    "high": 68.83,
    "low": 66.96,
    "close": 68.02,
    "volume": 9118089
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-14T09:49:06",
    "open": 64.52,
    "high": 64.97,
    "low": 63.88,
    "close": 64.72,
    "volume": 7665575
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-15T09:49:06",
    "open": 67.23,
    "high": 68.72,
    "low": 66.21,
    "close": 67.44,
    "volume": 4357174
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-16T09:49:06",
    "open": 69.32,
    "high": 70.42,
    "low": 67.99,
    "close": 69.78,
    "volume": 7009998
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-17T09:49:06",
    "open": 68.05,
    "high": 68.99,
    "low": 67.59,
    "close": 68.37,
    "volume": 340950
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-18T09:49:06",
    "open": 67.17,
    "high": 67.48,
    "low": 67.09,
    "close": 67.1,
    "volume": 5511641
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-19T09:49:06",
    "open": 64.03,
    "high": 65.1,
    "low": 63.12,
    "close": 64.3,
    "volume": 5904711
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-20T09:49:06",
    "open": 64.71,
    "high": 65.62,
    "low": 63.61,
    "close": 65.13,
    "volume": 2780910
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-21T09:49:06",
    "open": 67.79,
    "high": 69.38,
    "low": 67.22,
    "close": 68.06,
    "volume": 4424182
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-22T09:49:06",
    "open": 69.68,
    "high": 70.87,
    "low": 69.52,
    "close": 69.96,
    "volume": 2180187
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-23T09:49:06",
    "open": 67.08,
    "high": 67.3,
    "low": 66.59,
    "close": 67.23,
    "volume": 6731018
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-24T09:49:06",
    "open": 69.56,
    "high": 69.76,
    "low": 68.62,
    "close": 69.54,
    "volume": 7842127
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-25T09:49:06",
    "open": 68.24,
    "high": 69.07,
    "low": 67.65,
    "close": 68.19,
    "volume": 7338403
  },
  {
    "ticker": "ETHUSD",
    "datetime": "2025-07-26T09:49:06",
    "open": 70.08,
    "high": 71.63,
    "low": 68.82,
    "close": 70.35,
    "volume": 1709768
  }
]

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_RIO_hourly_ohlcv_20250727.json
[
  {
    "ticker": "RIO",
    "datetime": "2025-07-20T09:49:06",
    "open": 72.77,
    "high": 74.2,
    "low": 72.57,
    "close": 72.77,
    "volume": 4802754
  },
  {
    "ticker": "RIO",
    "datetime": "2025-07-21T09:49:06",
    "open": 69.87,
    "high": 70.12,
    "low": 69.0,
    "close": 70.11,
    "volume": 3323744
  },
  {
    "ticker": "RIO",
    "datetime": "2025-07-22T09:49:06",
    "open": 68.85,
    "high": 69.75,
    "low": 67.67,
    "close": 68.95,
    "volume": 1289273
  },
  {
    "ticker": "RIO",
    "datetime": "2025-07-23T09:49:06",
    "open": 72.27,
    "high": 73.26,
    "low": 70.98,
    "close": 72.08,
    "volume": 8835177
  },
  {
    "ticker": "RIO",
    "datetime": "2025-07-24T09:49:06",
    "open": 73.5,
    "high": 73.51,
    "low": 72.83,
    "close": 73.36,
    "volume": 6140808
  },
  {
    "ticker": "RIO",
    "datetime": "2025-07-25T09:49:06",
    "open": 73.61,
    "high": 74.12,
    "low": 72.94,
    "close": 73.07,
    "volume": 628669
  },
  {
    "ticker": "RIO",
    "datetime": "2025-07-26T09:49:06",
    "open": 75.48,
    "high": 76.84,
    "low": 75.25,
    "close": 76.0,
    "volume": 2862579
  }
]

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_JPM_daily_ohlcv_20250727.json
[
  {
    "ticker": "JPM",
    "datetime": "2025-06-27T09:49:06",
    "open": 135.52,
    "high": 137.39,
    "low": 134.41,
    "close": 135.2,
    "volume": 7806375
  },
  {
    "ticker": "JPM",
    "datetime": "2025-06-28T09:49:06",
    "open": 141.1,
    "high": 142.04,
    "low": 140.32,
    "close": 141.15,
    "volume": 4025645
  },
  {
    "ticker": "JPM",
    "datetime": "2025-06-29T09:49:06",
    "open": 134.37,
    "high": 135.19,
    "low": 133.84,
    "close": 134.22,
    "volume": 9381398
  },
  {
    "ticker": "JPM",
    "datetime": "2025-06-30T09:49:06",
    "open": 131.62,
    "high": 132.83,
    "low": 130.39,
    "close": 132.51,
    "volume": 8067263
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-01T09:49:06",
    "open": 130.32,
    "high": 130.66,
    "low": 129.73,
    "close": 130.17,
    "volume": 9587395
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-02T09:49:06",
    "open": 130.06,
    "high": 130.95,
    "low": 126.74,
    "close": 129.19,
    "volume": 8500928
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-03T09:49:06",
    "open": 134.64,
    "high": 138.16,
    "low": 133.59,
    "close": 135.5,
    "volume": 5016288
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-04T09:49:06",
    "open": 138.44,
    "high": 140.44,
    "low": 136.09,
    "close": 138.08,
    "volume": 7198012
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-05T09:49:06",
    "open": 139.31,
    "high": 139.5,
    "low": 138.7,
    "close": 139.3,
    "volume": 6317577
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-06T09:49:06",
    "open": 142.28,
    "high": 143.21,
    "low": 140.95,
    "close": 142.61,
    "volume": 2258405
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-07T09:49:06",
    "open": 149.74,
    "high": 151.07,
    "low": 147.31,
    "close": 148.51,
    "volume": 8896861
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-08T09:49:06",
    "open": 155.92,
    "high": 158.07,
    "low": 152.79,
    "close": 155.77,
    "volume": 6396971
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-09T09:49:06",
    "open": 152.79,
    "high": 153.76,
    "low": 151.56,
    "close": 152.01,
    "volume": 6282259
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-10T09:49:06",
    "open": 148.56,
    "high": 150.73,
    "low": 147.44,
    "close": 148.64,
    "volume": 3309762
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-11T09:49:06",
    "open": 150.14,
    "high": 152.35,
    "low": 148.01,
    "close": 149.33,
    "volume": 3264113
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-12T09:49:06",
    "open": 147.75,
    "high": 148.14,
    "low": 147.41,
    "close": 147.53,
    "volume": 2591627
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-13T09:49:06",
    "open": 150.46,
    "high": 151.7,
    "low": 147.73,
    "close": 150.21,
    "volume": 2887017
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-14T09:49:06",
    "open": 146.91,
    "high": 149.42,
    "low": 144.58,
    "close": 147.36,
    "volume": 3707585
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-15T09:49:06",
    "open": 148.51,
    "high": 150.79,
    "low": 148.48,
    "close": 149.57,
    "volume": 5729903
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-16T09:49:06",
    "open": 152.95,
    "high": 153.78,
    "low": 150.65,
    "close": 153.6,
    "volume": 1122507
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-17T09:49:06",
    "open": 154.83,
    "high": 156.84,
    "low": 152.42,
    "close": 155.37,
    "volume": 3404326
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-18T09:49:06",
    "open": 151.06,
    "high": 152.75,
    "low": 149.54,
    "close": 151.96,
    "volume": 9051550
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-19T09:49:06",
    "open": 154.78,
    "high": 155.89,
    "low": 153.41,
    "close": 154.44,
    "volume": 9645436
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-20T09:49:06",
    "open": 159.92,
    "high": 161.95,
    "low": 157.56,
    "close": 159.81,
    "volume": 5057946
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-21T09:49:06",
    "open": 154.81,
    "high": 157.93,
    "low": 154.12,
    "close": 155.05,
    "volume": 2341416
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-22T09:49:06",
    "open": 152.03,
    "high": 153.69,
    "low": 151.04,
    "close": 153.07,
    "volume": 2077477
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-23T09:49:06",
    "open": 155.43,
    "high": 157.14,
    "low": 154.66,
    "close": 155.41,
    "volume": 724301
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-24T09:49:06",
    "open": 161.31,
    "high": 163.1,
    "low": 159.1,
    "close": 161.36,
    "volume": 6072919
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-25T09:49:06",
    "open": 152.94,
    "high": 155.33,
    "low": 151.56,
    "close": 152.71,
    "volume": 5793050
  },
  {
    "ticker": "JPM",
    "datetime": "2025-07-26T09:49:06",
    "open": 160.33,
    "high": 162.88,
    "low": 157.2,
    "close": 159.24,
    "volume": 2083410
  }
]

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_V_hourly_ohlcv_20250727.json
[
  {
    "ticker": "V",
    "datetime": "2025-07-20T09:49:06",
    "open": 132.76,
    "high": 133.83,
    "low": 131.98,
    "close": 132.23,
    "volume": 7133693
  },
  {
    "ticker": "V",
    "datetime": "2025-07-21T09:49:06",
    "open": 131.08,
    "high": 131.58,
    "low": 128.41,
    "close": 130.5,
    "volume": 9135974
  },
  {
    "ticker": "V",
    "datetime": "2025-07-22T09:49:06",
    "open": 131.43,
    "high": 133.42,
    "low": 129.52,
    "close": 131.61,
    "volume": 3808961
  },
  {
    "ticker": "V",
    "datetime": "2025-07-23T09:49:06",
    "open": 133.42,
    "high": 133.45,
    "low": 132.36,
    "close": 133.23,
    "volume": 5880685
  },
  {
    "ticker": "V",
    "datetime": "2025-07-24T09:49:06",
    "open": 136.15,
    "high": 136.24,
    "low": 134.17,
    "close": 135.46,
    "volume": 8290064
  },
  {
    "ticker": "V",
    "datetime": "2025-07-25T09:49:06",
    "open": 135.75,
    "high": 137.78,
    "low": 133.94,
    "close": 136.34,
    "volume": 5481087
  },
  {
    "ticker": "V",
    "datetime": "2025-07-26T09:49:06",
    "open": 130.39,
    "high": 130.77,
    "low": 127.41,
    "close": 129.98,
    "volume": 289085
  }
]

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_GOOGL_daily_ohlcv_20250727.json
[
  {
    "ticker": "GOOGL",
    "datetime": "2025-06-27T09:49:06",
    "open": 356.37,
    "high": 358.19,
    "low": 351.31,
    "close": 357.23,
    "volume": 6180082
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-06-28T09:49:06",
    "open": 340.54,
    "high": 347.7,
    "low": 339.9,
    "close": 343.24,
    "volume": 5891045
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-06-29T09:49:06",
    "open": 335.36,
    "high": 343.21,
    "low": 331.47,
    "close": 338.1,
    "volume": 3202937
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-06-30T09:49:06",
    "open": 346.29,
    "high": 354.52,
    "low": 342.31,
    "close": 348.21,
    "volume": 2748137
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-01T09:49:06",
    "open": 355.87,
    "high": 356.51,
    "low": 351.31,
    "close": 354.74,
    "volume": 3412134
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-02T09:49:06",
    "open": 367.32,
    "high": 368.68,
    "low": 359.44,
    "close": 364.55,
    "volume": 3975144
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-03T09:49:06",
    "open": 371.61,
    "high": 374.51,
    "low": 370.68,
    "close": 371.25,
    "volume": 4539974
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-04T09:49:06",
    "open": 384.88,
    "high": 386.17,
    "low": 382.15,
    "close": 384.27,
    "volume": 1711035
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-05T09:49:06",
    "open": 392.49,
    "high": 392.88,
    "low": 387.77,
    "close": 390.36,
    "volume": 6519662
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-06T09:49:06",
    "open": 398.98,
    "high": 402.26,
    "low": 395.2,
    "close": 397.0,
    "volume": 1500227
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-07T09:49:06",
    "open": 415.59,
    "high": 419.38,
    "low": 408.55,
    "close": 413.9,
    "volume": 5110975
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-08T09:49:06",
    "open": 428.03,
    "high": 435.94,
    "low": 422.77,
    "close": 430.3,
    "volume": 6555988
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-09T09:49:06",
    "open": 412.6,
    "high": 415.38,
    "low": 404.63,
    "close": 412.1,
    "volume": 841598
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-10T09:49:06",
    "open": 431.16,
    "high": 438.49,
    "low": 426.36,
    "close": 429.5,
    "volume": 2955789
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-11T09:49:06",
    "open": 449.65,
    "high": 451.6,
    "low": 443.4,
    "close": 449.04,
    "volume": 4372880
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-12T09:49:06",
    "open": 446.46,
    "high": 446.77,
    "low": 444.72,
    "close": 444.95,
    "volume": 2431422
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-13T09:49:06",
    "open": 457.43,
    "high": 460.81,
    "low": 455.22,
    "close": 460.4,
    "volume": 1679079
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-14T09:49:06",
    "open": 459.8,
    "high": 462.13,
    "low": 457.74,
    "close": 461.76,
    "volume": 5521127
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-15T09:49:06",
    "open": 467.16,
    "high": 467.65,
    "low": 461.02,
    "close": 466.62,
    "volume": 228386
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-16T09:49:06",
    "open": 481.11,
    "high": 485.39,
    "low": 475.55,
    "close": 481.95,
    "volume": 1039099
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-17T09:49:06",
    "open": 469.72,
    "high": 474.13,
    "low": 467.79,
    "close": 470.29,
    "volume": 4846324
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-18T09:49:06",
    "open": 455.49,
    "high": 457.92,
    "low": 453.03,
    "close": 455.11,
    "volume": 2619960
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-19T09:49:06",
    "open": 478.99,
    "high": 486.45,
    "low": 472.5,
    "close": 478.0,
    "volume": 5564203
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-20T09:49:06",
    "open": 459.59,
    "high": 465.2,
    "low": 458.46,
    "close": 461.95,
    "volume": 4218396
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-21T09:49:06",
    "open": 452.73,
    "high": 461.13,
    "low": 450.63,
    "close": 451.14,
    "volume": 5790819
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-22T09:49:06",
    "open": 428.47,
    "high": 434.25,
    "low": 427.41,
    "close": 430.01,
    "volume": 1578707
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-23T09:49:06",
    "open": 408.95,
    "high": 414.51,
    "low": 401.88,
    "close": 407.32,
    "volume": 1185354
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-24T09:49:06",
    "open": 415.62,
    "high": 416.57,
    "low": 407.75,
    "close": 415.33,
    "volume": 1237350
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-25T09:49:06",
    "open": 430.04,
    "high": 430.8,
    "low": 427.02,
    "close": 428.48,
    "volume": 4030971
  },
  {
    "ticker": "GOOGL",
    "datetime": "2025-07-26T09:49:06",
    "open": 420.83,
    "high": 427.75,
    "low": 414.73,
    "close": 420.73,
    "volume": 2231138
  }
]

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_AMZN_daily_ohlcv_20250727.json
[
  {
    "ticker": "AMZN",
    "datetime": "2025-06-27T09:49:06",
    "open": 85.52,
    "high": 85.84,
    "low": 85.01,
    "close": 85.55,
    "volume": 3805809
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-06-28T09:49:06",
    "open": 85.16,
    "high": 86.08,
    "low": 83.48,
    "close": 84.96,
    "volume": 5987705
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-06-29T09:49:06",
    "open": 87.79,
    "high": 89.98,
    "low": 87.22,
    "close": 88.38,
    "volume": 9051626
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-06-30T09:49:06",
    "open": 89.05,
    "high": 90.58,
    "low": 87.67,
    "close": 88.72,
    "volume": 5949155
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-01T09:49:06",
    "open": 92.98,
    "high": 93.73,
    "low": 92.51,
    "close": 93.46,
    "volume": 7174789
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-02T09:49:06",
    "open": 91.31,
    "high": 92.48,
    "low": 91.15,
    "close": 91.17,
    "volume": 454470
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-03T09:49:06",
    "open": 93.42,
    "high": 95.24,
    "low": 92.82,
    "close": 93.49,
    "volume": 5032228
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-04T09:49:06",
    "open": 95.77,
    "high": 97.94,
    "low": 95.62,
    "close": 96.16,
    "volume": 3932047
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-05T09:49:06",
    "open": 99.82,
    "high": 100.24,
    "low": 98.58,
    "close": 99.39,
    "volume": 5499004
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-06T09:49:06",
    "open": 102.45,
    "high": 102.87,
    "low": 102.27,
    "close": 102.7,
    "volume": 1077228
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-07T09:49:06",
    "open": 106.03,
    "high": 107.88,
    "low": 104.43,
    "close": 105.14,
    "volume": 9690220
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-08T09:49:06",
    "open": 108.96,
    "high": 110.47,
    "low": 107.94,
    "close": 108.9,
    "volume": 3107385
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-09T09:49:06",
    "open": 114.16,
    "high": 115.12,
    "low": 113.97,
    "close": 114.23,
    "volume": 686425
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-10T09:49:06",
    "open": 112.26,
    "high": 112.82,
    "low": 112.14,
    "close": 112.56,
    "volume": 7299124
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-11T09:49:06",
    "open": 113.98,
    "high": 116.38,
    "low": 113.92,
    "close": 114.38,
    "volume": 7956412
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-12T09:49:06",
    "open": 116.57,
    "high": 118.15,
    "low": 114.9,
    "close": 116.27,
    "volume": 6666771
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-13T09:49:06",
    "open": 113.98,
    "high": 115.32,
    "low": 113.5,
    "close": 114.19,
    "volume": 3927442
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-14T09:49:06",
    "open": 113.34,
    "high": 113.97,
    "low": 111.48,
    "close": 113.3,
    "volume": 6333273
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-15T09:49:06",
    "open": 108.87,
    "high": 110.33,
    "low": 106.19,
    "close": 108.13,
    "volume": 623337
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-16T09:49:06",
    "open": 112.78,
    "high": 113.41,
    "low": 111.08,
    "close": 112.77,
    "volume": 6246861
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-17T09:49:06",
    "open": 111.5,
    "high": 112.45,
    "low": 108.94,
    "close": 111.05,
    "volume": 352547
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-18T09:49:06",
    "open": 110.1,
    "high": 110.84,
    "low": 109.72,
    "close": 109.85,
    "volume": 5743954
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-19T09:49:06",
    "open": 112.05,
    "high": 112.87,
    "low": 111.21,
    "close": 111.66,
    "volume": 8406453
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-20T09:49:06",
    "open": 110.7,
    "high": 111.39,
    "low": 109.42,
    "close": 110.81,
    "volume": 776132
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-21T09:49:06",
    "open": 106.86,
    "high": 107.07,
    "low": 105.24,
    "close": 106.79,
    "volume": 9063622
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-22T09:49:06",
    "open": 110.5,
    "high": 111.95,
    "low": 109.13,
    "close": 110.0,
    "volume": 3751737
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-23T09:49:06",
    "open": 108.67,
    "high": 109.27,
    "low": 107.53,
    "close": 108.87,
    "volume": 8007283
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-24T09:49:06",
    "open": 106.78,
    "high": 107.92,
    "low": 106.14,
    "close": 107.0,
    "volume": 491901
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-25T09:49:06",
    "open": 105.33,
    "high": 107.62,
    "low": 103.38,
    "close": 105.65,
    "volume": 5091619
  },
  {
    "ticker": "AMZN",
    "datetime": "2025-07-26T09:49:06",
    "open": 106.49,
    "high": 107.41,
    "low": 104.7,
    "close": 106.98,
    "volume": 5076387
  }
]

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_NVDA_hourly_ohlcv_20250727.json
[
  {
    "ticker": "NVDA",
    "datetime": "2025-07-20T09:49:06",
    "open": 319.52,
    "high": 320.61,
    "low": 316.68,
    "close": 317.83,
    "volume": 5509530
  },
  {
    "ticker": "NVDA",
    "datetime": "2025-07-21T09:49:06",
    "open": 323.05,
    "high": 323.2,
    "low": 320.74,
    "close": 321.43,
    "volume": 766460
  },
  {
    "ticker": "NVDA",
    "datetime": "2025-07-22T09:49:06",
    "open": 328.0,
    "high": 328.62,
    "low": 324.92,
    "close": 326.47,
    "volume": 4500840
  },
  {
    "ticker": "NVDA",
    "datetime": "2025-07-23T09:49:06",
    "open": 326.16,
    "high": 329.13,
    "low": 319.3,
    "close": 325.02,
    "volume": 1087661
  },
  {
    "ticker": "NVDA",
    "datetime": "2025-07-24T09:49:06",
    "open": 322.53,
    "high": 323.98,
    "low": 316.59,
    "close": 322.85,
    "volume": 9771164
  },
  {
    "ticker": "NVDA",
    "datetime": "2025-07-25T09:49:06",
    "open": 323.92,
    "high": 330.07,
    "low": 317.57,
    "close": 325.39,
    "volume": 9225312
  },
  {
    "ticker": "NVDA",
    "datetime": "2025-07-26T09:49:06",
    "open": 322.75,
    "high": 328.36,
    "low": 321.83,
    "close": 321.89,
    "volume": 3175438
  }
]
