=== DLawls/trading-platform/financial_data_collector/yahoo_finance_collector/schema/ohlcv.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "OHLCV Data",
  "type": "object",
  "properties": {
    "ticker": {"type": "string"},
    "datetime": {"type": "string", "format": "date-time"},
    "open": {"type": "number"},
    "high": {"type": "number"},
    "low": {"type": "number"},
    "close": {"type": "number"},
    "volume": {"type": "number"}
  },
  "required": ["ticker", "datetime", "open", "high", "low", "close", "volume"]
}

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_TSLA_daily_ohlcv_20250727.json
[
  {
    "ticker": "TSLA",
    "datetime": "2025-06-27T09:49:06",
    "open": 417.85,
    "high": 427.04,
    "low": 414.92,
    "close": 419.67,
    "volume": 2849747
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-06-28T09:49:06",
    "open": 409.75,
    "high": 412.17,
    "low": 404.28,
    "close": 408.2,
    "volume": 208493
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-06-29T09:49:06",
    "open": 398.45,
    "high": 406.1,
    "low": 390.15,
    "close": 397.05,
    "volume": 6922361
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-06-30T09:49:06",
    "open": 388.93,
    "high": 389.38,
    "low": 381.0,
    "close": 388.64,
    "volume": 7517952
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-01T09:49:06",
    "open": 384.11,
    "high": 393.52,
    "low": 381.77,
    "close": 386.65,
    "volume": 9237849
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-02T09:49:06",
    "open": 378.97,
    "high": 384.28,
    "low": 378.36,
    "close": 380.54,
    "volume": 5665515
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-03T09:49:06",
    "open": 372.87,
    "high": 379.54,
    "low": 366.05,
    "close": 373.43,
    "volume": 8061277
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-04T09:49:06",
    "open": 370.57,
    "high": 376.03,
    "low": 365.3,
    "close": 369.59,
    "volume": 8491494
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-05T09:49:06",
    "open": 357.29,
    "high": 361.34,
    "low": 353.29,
    "close": 359.04,
    "volume": 1268666
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-06T09:49:06",
    "open": 362.42,
    "high": 368.88,
    "low": 358.96,
    "close": 363.85,
    "volume": 3452541
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-07T09:49:06",
    "open": 355.09,
    "high": 360.65,
    "low": 348.84,
    "close": 358.61,
    "volume": 9821009
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-08T09:49:06",
    "open": 366.86,
    "high": 371.26,
    "low": 365.84,
    "close": 366.01,
    "volume": 3426908
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-09T09:49:06",
    "open": 375.95,
    "high": 383.69,
    "low": 374.56,
    "close": 376.73,
    "volume": 8632212
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-10T09:49:06",
    "open": 356.41,
    "high": 363.08,
    "low": 351.54,
    "close": 357.39,
    "volume": 8826597
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-11T09:49:06",
    "open": 361.25,
    "high": 367.3,
    "low": 355.34,
    "close": 360.72,
    "volume": 2574604
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-12T09:49:06",
    "open": 344.59,
    "high": 350.4,
    "low": 338.84,
    "close": 345.89,
    "volume": 2472223
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-13T09:49:06",
    "open": 333.57,
    "high": 339.64,
    "low": 333.43,
    "close": 333.85,
    "volume": 6824727
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-14T09:49:06",
    "open": 338.91,
    "high": 343.47,
    "low": 333.87,
    "close": 338.9,
    "volume": 683396
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-15T09:49:06",
    "open": 331.2,
    "high": 334.37,
    "low": 325.53,
    "close": 331.53,
    "volume": 7238015
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-16T09:49:06",
    "open": 315.8,
    "high": 321.47,
    "low": 311.74,
    "close": 316.77,
    "volume": 143254
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-17T09:49:06",
    "open": 314.99,
    "high": 319.05,
    "low": 310.89,
    "close": 316.23,
    "volume": 5820745
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-18T09:49:06",
    "open": 325.79,
    "high": 328.1,
    "low": 323.65,
    "close": 327.01,
    "volume": 7032440
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-19T09:49:06",
    "open": 311.98,
    "high": 312.02,
    "low": 306.45,
    "close": 310.95,
    "volume": 1965960
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-20T09:49:06",
    "open": 318.96,
    "high": 319.49,
    "low": 313.72,
    "close": 318.86,
    "volume": 4752510
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-21T09:49:06",
    "open": 320.02,
    "high": 321.58,
    "low": 314.78,
    "close": 317.87,
    "volume": 169097
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-22T09:49:06",
    "open": 319.44,
    "high": 320.22,
    "low": 317.97,
    "close": 320.07,
    "volume": 5485540
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-23T09:49:06",
    "open": 304.79,
    "high": 304.88,
    "low": 298.87,
    "close": 303.25,
    "volume": 5352463
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-24T09:49:06",
    "open": 295.48,
    "high": 297.31,
    "low": 293.3,
    "close": 296.32,
    "volume": 8321974
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-25T09:49:06",
    "open": 284.76,
    "high": 285.39,
    "low": 277.62,
    "close": 283.21,
    "volume": 4440220
  },
  {
    "ticker": "TSLA",
    "datetime": "2025-07-26T09:49:06",
    "open": 275.0,
    "high": 280.32,
    "low": 272.41,
    "close": 276.86,
    "volume": 9871469
  }
]

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_META_hourly_ohlcv_20250727.json
[
  {
    "ticker": "META",
    "datetime": "2025-07-20T09:49:06",
    "open": 402.6,
    "high": 405.01,
    "low": 401.84,
    "close": 402.82,
    "volume": 2697302
  },
  {
    "ticker": "META",
    "datetime": "2025-07-21T09:49:06",
    "open": 401.2,
    "high": 407.78,
    "low": 393.21,
    "close": 403.3,
    "volume": 6703358
  },
  {
    "ticker": "META",
    "datetime": "2025-07-22T09:49:06",
    "open": 416.71,
    "high": 423.55,
    "low": 413.91,
    "close": 414.85,
    "volume": 552211
  },
  {
    "ticker": "META",
    "datetime": "2025-07-23T09:49:06",
    "open": 405.9,
    "high": 415.94,
    "low": 398.8,
    "close": 408.91,
    "volume": 1308027
  },
  {
    "ticker": "META",
    "datetime": "2025-07-24T09:49:06",
    "open": 407.65,
    "high": 411.01,
    "low": 402.2,
    "close": 405.53,
    "volume": 9154951
  },
  {
    "ticker": "META",
    "datetime": "2025-07-25T09:49:06",
    "open": 404.65,
    "high": 409.57,
    "low": 403.11,
    "close": 405.32,
    "volume": 2934117
  },
  {
    "ticker": "META",
    "datetime": "2025-07-26T09:49:06",
    "open": 423.69,
    "high": 430.86,
    "low": 414.34,
    "close": 422.5,
    "volume": 2393895
  }
]

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_AAPL_hourly_ohlcv_20250727.json
[
  {
    "ticker": "AAPL",
    "datetime": "2025-07-20T09:49:06",
    "open": 368.96,
    "high": 370.66,
    "low": 363.35,
    "close": 368.76,
    "volume": 7143816
  },
  {
    "ticker": "AAPL",
    "datetime": "2025-07-21T09:49:06",
    "open": 352.26,
    "high": 355.57,
    "low": 348.34,
    "close": 352.2,
    "volume": 1618896
  },
  {
    "ticker": "AAPL",
    "datetime": "2025-07-22T09:49:06",
    "open": 343.6,
    "high": 349.35,
    "low": 338.43,
    "close": 345.59,
    "volume": 431359
  },
  {
    "ticker": "AAPL",
    "datetime": "2025-07-23T09:49:06",
    "open": 359.89,
    "high": 365.53,
    "low": 357.34,
    "close": 358.87,
    "volume": 5616554
  },
  {
    "ticker": "AAPL",
    "datetime": "2025-07-24T09:49:06",
    "open": 341.61,
    "high": 346.01,
    "low": 340.09,
    "close": 342.12,
    "volume": 1846530
  },
  {
    "ticker": "AAPL",
    "datetime": "2025-07-25T09:49:06",
    "open": 349.04,
    "high": 356.53,
    "low": 346.78,
    "close": 350.18,
    "volume": 3330289
  },
  {
    "ticker": "AAPL",
    "datetime": "2025-07-26T09:49:06",
    "open": 354.95,
    "high": 360.06,
    "low": 349.27,
    "close": 353.57,
    "volume": 5163836
  }
]

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_BTCUSD_daily_ohlcv_20250727.json
[
  {
    "ticker": "BTCUSD",
    "datetime": "2025-06-27T09:49:06",
    "open": 65.24,
    "high": 65.45,
    "low": 64.27,
    "close": 64.76,
    "volume": 4045545
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-06-28T09:49:06",
    "open": 67.35,
    "high": 68.75,
    "low": 66.21,
    "close": 67.86,
    "volume": 1297374
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-06-29T09:49:06",
    "open": 67.41,
    "high": 68.76,
    "low": 66.42,
    "close": 67.52,
    "volume": 1080219
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-06-30T09:49:06",
    "open": 68.08,
    "high": 68.66,
    "low": 67.35,
    "close": 67.81,
    "volume": 9455841
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-01T09:49:06",
    "open": 67.89,
    "high": 68.21,
    "low": 67.53,
    "close": 67.71,
    "volume": 8889577
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-02T09:49:06",
    "open": 65.57,
    "high": 65.66,
    "low": 64.16,
    "close": 65.14,
    "volume": 4556328
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-03T09:49:06",
    "open": 64.22,
    "high": 64.6,
    "low": 63.33,
    "close": 64.02,
    "volume": 7586872
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-04T09:49:06",
    "open": 62.14,
    "high": 62.98,
    "low": 61.68,
    "close": 62.09,
    "volume": 1113246
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-05T09:49:06",
    "open": 62.44,
    "high": 62.92,
    "low": 61.39,
    "close": 62.36,
    "volume": 5910700
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-06T09:49:06",
    "open": 62.64,
    "high": 63.78,
    "low": 62.33,
    "close": 62.51,
    "volume": 5099886
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-07T09:49:06",
    "open": 63.76,
    "high": 64.33,
    "low": 63.65,
    "close": 63.89,
    "volume": 4279930
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-08T09:49:06",
    "open": 62.97,
    "high": 63.07,
    "low": 61.39,
    "close": 62.52,
    "volume": 3316832
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-09T09:49:06",
    "open": 65.24,
    "high": 65.78,
    "low": 64.29,
    "close": 65.56,
    "volume": 6406324
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-10T09:49:06",
    "open": 64.53,
    "high": 65.64,
    "low": 63.79,
    "close": 64.79,
    "volume": 3812945
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-11T09:49:06",
    "open": 64.68,
    "high": 64.77,
    "low": 64.56,
    "close": 64.69,
    "volume": 1705912
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-12T09:49:06",
    "open": 64.37,
    "high": 65.01,
    "low": 63.95,
    "close": 64.2,
    "volume": 9744487
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-13T09:49:06",
    "open": 62.86,
    "high": 64.51,
    "low": 62.6,
    "close": 63.32,
    "volume": 1208232
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-14T09:49:06",
    "open": 60.23,
    "high": 61.3,
    "low": 59.32,
    "close": 60.16,
    "volume": 4120597
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-15T09:49:06",
    "open": 57.71,
    "high": 58.86,
    "low": 57.01,
    "close": 58.23,
    "volume": 2186556
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-16T09:49:06",
    "open": 57.66,
    "high": 57.75,
    "low": 56.39,
    "close": 57.4,
    "volume": 1195597
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-17T09:49:06",
    "open": 58.53,
    "high": 58.74,
    "low": 57.96,
    "close": 58.54,
    "volume": 6055186
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-18T09:49:06",
    "open": 59.69,
    "high": 60.89,
    "low": 58.81,
    "close": 60.06,
    "volume": 2468879
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-19T09:49:06",
    "open": 60.02,
    "high": 61.09,
    "low": 59.43,
    "close": 60.19,
    "volume": 8062425
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-20T09:49:06",
    "open": 58.95,
    "high": 59.92,
    "low": 58.58,
    "close": 59.4,
    "volume": 8647117
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-21T09:49:06",
    "open": 58.7,
    "high": 59.09,
    "low": 58.65,
    "close": 58.8,
    "volume": 4176887
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-22T09:49:06",
    "open": 58.05,
    "high": 59.21,
    "low": 57.85,
    "close": 58.22,
    "volume": 314867
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-23T09:49:06",
    "open": 61.17,
    "high": 61.94,
    "low": 60.31,
    "close": 60.62,
    "volume": 7499191
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-24T09:49:06",
    "open": 58.4,
    "high": 59.22,
    "low": 57.5,
    "close": 58.55,
    "volume": 9985467
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-25T09:49:06",
    "open": 55.8,
    "high": 56.21,
    "low": 54.57,
    "close": 55.48,
    "volume": 434968
  },
  {
    "ticker": "BTCUSD",
    "datetime": "2025-07-26T09:49:06",
    "open": 55.81,
    "high": 56.35,
    "low": 55.61,
    "close": 55.61,
    "volume": 5579328
  }
]

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_SOLUSD_daily_ohlcv_20250727.json
[
  {
    "ticker": "SOLUSD",
    "datetime": "2025-06-27T09:49:06",
    "open": 288.18,
    "high": 292.86,
    "low": 287.23,
    "close": 288.35,
    "volume": 1223067
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-06-28T09:49:06",
    "open": 286.68,
    "high": 292.49,
    "low": 284.47,
    "close": 289.01,
    "volume": 5248441
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-06-29T09:49:06",
    "open": 274.33,
    "high": 279.91,
    "low": 274.03,
    "close": 274.49,
    "volume": 8765508
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-06-30T09:49:06",
    "open": 272.45,
    "high": 279.99,
    "low": 270.36,
    "close": 274.68,
    "volume": 1821253
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-01T09:49:06",
    "open": 280.75,
    "high": 282.45,
    "low": 276.71,
    "close": 279.19,
    "volume": 4025827
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-02T09:49:06",
    "open": 291.99,
    "high": 296.47,
    "low": 288.22,
    "close": 293.27,
    "volume": 8523997
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-03T09:49:06",
    "open": 297.52,
    "high": 300.88,
    "low": 297.05,
    "close": 298.47,
    "volume": 1179535
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-04T09:49:06",
    "open": 308.7,
    "high": 310.95,
    "low": 303.05,
    "close": 307.92,
    "volume": 5040078
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-05T09:49:06",
    "open": 306.36,
    "high": 308.11,
    "low": 300.79,
    "close": 306.95,
    "volume": 8504527
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-06T09:49:06",
    "open": 308.65,
    "high": 313.2,
    "low": 304.3,
    "close": 309.8,
    "volume": 7896097
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-07T09:49:06",
    "open": 308.04,
    "high": 313.97,
    "low": 301.59,
    "close": 307.49,
    "volume": 8257526
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-08T09:49:06",
    "open": 310.09,
    "high": 315.76,
    "low": 309.94,
    "close": 312.37,
    "volume": 1332137
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-09T09:49:06",
    "open": 304.56,
    "high": 308.72,
    "low": 303.48,
    "close": 306.07,
    "volume": 9928173
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-10T09:49:06",
    "open": 307.44,
    "high": 312.82,
    "low": 301.66,
    "close": 306.32,
    "volume": 1419844
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-11T09:49:06",
    "open": 301.67,
    "high": 305.07,
    "low": 298.38,
    "close": 301.79,
    "volume": 4079955
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-12T09:49:06",
    "open": 289.81,
    "high": 292.76,
    "low": 287.26,
    "close": 289.82,
    "volume": 7031576
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-13T09:49:06",
    "open": 287.37,
    "high": 291.38,
    "low": 282.9,
    "close": 288.2,
    "volume": 6374121
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-14T09:49:06",
    "open": 294.62,
    "high": 296.03,
    "low": 290.8,
    "close": 295.34,
    "volume": 6337825
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-15T09:49:06",
    "open": 288.85,
    "high": 292.71,
    "low": 283.57,
    "close": 290.16,
    "volume": 5368625
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-16T09:49:06",
    "open": 302.16,
    "high": 304.71,
    "low": 299.99,
    "close": 301.65,
    "volume": 7465282
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-17T09:49:06",
    "open": 289.63,
    "high": 295.12,
    "low": 285.92,
    "close": 288.82,
    "volume": 9784303
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-18T09:49:06",
    "open": 301.42,
    "high": 305.5,
    "low": 295.8,
    "close": 302.55,
    "volume": 4631848
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-19T09:49:06",
    "open": 298.83,
    "high": 303.57,
    "low": 297.54,
    "close": 301.5,
    "volume": 7937582
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-20T09:49:06",
    "open": 286.58,
    "high": 288.07,
    "low": 281.05,
    "close": 287.39,
    "volume": 3581645
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-21T09:49:06",
    "open": 286.52,
    "high": 289.21,
    "low": 283.78,
    "close": 287.22,
    "volume": 4462516
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-22T09:49:06",
    "open": 277.71,
    "high": 282.6,
    "low": 275.94,
    "close": 280.03,
    "volume": 3786409
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-23T09:49:06",
    "open": 277.12,
    "high": 279.61,
    "low": 270.39,
    "close": 275.84,
    "volume": 8297533
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-24T09:49:06",
    "open": 278.87,
    "high": 281.16,
    "low": 274.11,
    "close": 278.54,
    "volume": 9085840
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-25T09:49:06",
    "open": 266.92,
    "high": 272.3,
    "low": 264.83,
    "close": 267.63,
    "volume": 5389021
  },
  {
    "ticker": "SOLUSD",
    "datetime": "2025-07-26T09:49:06",
    "open": 273.68,
    "high": 278.18,
    "low": 270.69,
    "close": 272.46,
    "volume": 8733833
  }
]

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_BHP_daily_ohlcv_20250727.json
[
  {
    "ticker": "BHP",
    "datetime": "2025-06-27T09:49:06",
    "open": 455.93,
    "high": 466.32,
    "low": 452.59,
    "close": 459.14,
    "volume": 9370601
  },
  {
    "ticker": "BHP",
    "datetime": "2025-06-28T09:49:06",
    "open": 442.65,
    "high": 448.26,
    "low": 434.81,
    "close": 442.3,
    "volume": 7367099
  },
  {
    "ticker": "BHP",
    "datetime": "2025-06-29T09:49:06",
    "open": 426.12,
    "high": 426.88,
    "low": 422.5,
    "close": 425.78,
    "volume": 9689816
  },
  {
    "ticker": "BHP",
    "datetime": "2025-06-30T09:49:06",
    "open": 441.71,
    "high": 448.4,
    "low": 441.22,
    "close": 442.17,
    "volume": 2937241
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-01T09:49:06",
    "open": 432.86,
    "high": 437.36,
    "low": 426.6,
    "close": 429.97,
    "volume": 6096762
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-02T09:49:06",
    "open": 426.48,
    "high": 432.74,
    "low": 420.32,
    "close": 428.21,
    "volume": 7085210
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-03T09:49:06",
    "open": 433.75,
    "high": 440.55,
    "low": 426.79,
    "close": 434.4,
    "volume": 4636431
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-04T09:49:06",
    "open": 444.88,
    "high": 451.7,
    "low": 443.19,
    "close": 444.32,
    "volume": 6185993
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-05T09:49:06",
    "open": 423.4,
    "high": 431.38,
    "low": 419.49,
    "close": 425.2,
    "volume": 1641494
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-06T09:49:06",
    "open": 409.79,
    "high": 411.66,
    "low": 403.53,
    "close": 409.57,
    "volume": 228672
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-07T09:49:06",
    "open": 426.96,
    "high": 433.5,
    "low": 419.32,
    "close": 425.67,
    "volume": 5720180
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-08T09:49:06",
    "open": 425.15,
    "high": 431.31,
    "low": 425.03,
    "close": 425.47,
    "volume": 7715022
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-09T09:49:06",
    "open": 442.97,
    "high": 450.83,
    "low": 442.35,
    "close": 445.71,
    "volume": 8089307
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-10T09:49:06",
    "open": 441.08,
    "high": 441.29,
    "low": 438.25,
    "close": 438.92,
    "volume": 8849575
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-11T09:49:06",
    "open": 419.4,
    "high": 420.58,
    "low": 416.22,
    "close": 419.95,
    "volume": 3265391
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-12T09:49:06",
    "open": 411.5,
    "high": 417.51,
    "low": 411.11,
    "close": 415.2,
    "volume": 8435852
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-13T09:49:06",
    "open": 412.75,
    "high": 414.56,
    "low": 404.15,
    "close": 411.74,
    "volume": 8951244
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-14T09:49:06",
    "open": 424.44,
    "high": 430.85,
    "low": 422.7,
    "close": 427.43,
    "volume": 4487207
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-15T09:49:06",
    "open": 415.54,
    "high": 420.8,
    "low": 414.21,
    "close": 416.65,
    "volume": 1191781
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-16T09:49:06",
    "open": 397.66,
    "high": 401.98,
    "low": 393.45,
    "close": 397.25,
    "volume": 1355842
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-17T09:49:06",
    "open": 396.18,
    "high": 400.31,
    "low": 390.52,
    "close": 396.16,
    "volume": 1790383
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-18T09:49:06",
    "open": 399.12,
    "high": 403.32,
    "low": 396.87,
    "close": 399.37,
    "volume": 8003657
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-19T09:49:06",
    "open": 397.74,
    "high": 404.63,
    "low": 396.31,
    "close": 400.78,
    "volume": 4380381
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-20T09:49:06",
    "open": 384.83,
    "high": 390.57,
    "low": 380.35,
    "close": 385.92,
    "volume": 4659063
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-21T09:49:06",
    "open": 388.29,
    "high": 392.61,
    "low": 385.23,
    "close": 390.16,
    "volume": 3445253
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-22T09:49:06",
    "open": 382.53,
    "high": 386.96,
    "low": 379.46,
    "close": 382.82,
    "volume": 743773
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-23T09:49:06",
    "open": 393.64,
    "high": 401.02,
    "low": 388.99,
    "close": 393.41,
    "volume": 5490495
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-24T09:49:06",
    "open": 389.18,
    "high": 392.22,
    "low": 385.94,
    "close": 389.98,
    "volume": 6748947
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-25T09:49:06",
    "open": 404.53,
    "high": 408.84,
    "low": 397.43,
    "close": 406.89,
    "volume": 8890988
  },
  {
    "ticker": "BHP",
    "datetime": "2025-07-26T09:49:06",
    "open": 393.86,
    "high": 393.86,
    "low": 393.04,
    "close": 393.31,
    "volume": 3545037
  }
]

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_MSFT_hourly_ohlcv_20250727.json
[
  {
    "ticker": "MSFT",
    "datetime": "2025-07-20T09:49:06",
    "open": 438.49,
    "high": 443.1,
    "low": 427.03,
    "close": 434.65,
    "volume": 3798326
  },
  {
    "ticker": "MSFT",
    "datetime": "2025-07-21T09:49:06",
    "open": 417.34,
    "high": 423.5,
    "low": 416.49,
    "close": 418.68,
    "volume": 6312270
  },
  {
    "ticker": "MSFT",
    "datetime": "2025-07-22T09:49:06",
    "open": 418.98,
    "high": 419.25,
    "low": 416.8,
    "close": 418.9,
    "volume": 821875
  },
  {
    "ticker": "MSFT",
    "datetime": "2025-07-23T09:49:06",
    "open": 425.96,
    "high": 433.38,
    "low": 420.85,
    "close": 428.58,
    "volume": 7670828
  },
  {
    "ticker": "MSFT",
    "datetime": "2025-07-24T09:49:06",
    "open": 411.6,
    "high": 422.03,
    "low": 410.09,
    "close": 415.5,
    "volume": 9687553
  },
  {
    "ticker": "MSFT",
    "datetime": "2025-07-25T09:49:06",
    "open": 423.58,
    "high": 424.11,
    "low": 417.93,
    "close": 421.41,
    "volume": 4364496
  },
  {
    "ticker": "MSFT",
    "datetime": "2025-07-26T09:49:06",
    "open": 436.21,
    "high": 436.56,
    "low": 425.45,
    "close": 432.35,
    "volume": 9049966
  }
]
