=== DLawls/trading-platform/financial_data_collector/yahoo_finance_collector/schema/ohlcv.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "OHLCV Data",
  "type": "object",
  "properties": {
    "ticker": {"type": "string"},
    "datetime": {"type": "string", "format": "date-time"},
    "open": {"type": "number"},
    "high": {"type": "number"},
    "low": {"type": "number"},
    "close": {"type": "number"},
    "volume": {"type": "number"}
  },
  "required": ["ticker", "datetime", "open", "high", "low", "close", "volume"]
}

=== DLawls/trading-platform/financial_data_collector/financial_data/ohlcv/mock_UNH_daily_ohlcv_20250727.json
[
  {
    "ticker": "UNH",
    "datetime": "2025-06-27T09:49:06",
    "open": 345.2,
    "high": 350.74,
    "low": 339.68,
    "close": 345.48,
    "volume": 3899988
  },
  {
    "ticker": "UNH",
    "datetime": "2025-06-28T09:49:06",
    "open": 347.91,
    "high": 350.58,
    "low": 345.07,
    "close": 345.75,
    "volume": 6808711
  },
  {
    "ticker": "UNH",
    "datetime": "2025-06-29T09:49:06",
    "open": 334.16,
    "high": 341.05,
    "low": 330.9,
    "close": 334.99,
    "volume": 1452253
  },
  {
    "ticker": "UNH",
    "datetime": "2025-06-30T09:49:06",
    "open": 319.72,
    "high": 326.97,
    "low": 314.14,
    "close": 322.31,
    "volume": 4244040
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-01T09:49:06",
    "open": 329.81,
    "high": 330.44,
    "low": 325.3,
    "close": 329.9,
    "volume": 3012641
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-02T09:49:06",
    "open": 319.08,
    "high": 323.18,
    "low": 316.65,
    "close": 318.91,
    "volume": 1658355
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-03T09:49:06",
    "open": 326.73,
    "high": 331.1,
    "low": 322.17,
    "close": 328.78,
    "volume": 1862565
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-04T09:49:06",
    "open": 318.18,
    "high": 318.94,
    "low": 315.7,
    "close": 318.69,
    "volume": 5999864
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-05T09:49:06",
    "open": 302.33,
    "high": 308.66,
    "low": 301.14,
    "close": 302.75,
    "volume": 5988363
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-06T09:49:06",
    "open": 288.13,
    "high": 291.32,
    "low": 284.7,
    "close": 289.61,
    "volume": 1402804
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-07T09:49:06",
    "open": 277.44,
    "high": 283.29,
    "low": 273.95,
    "close": 278.74,
    "volume": 8428628
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-08T09:49:06",
    "open": 266.94,
    "high": 272.4,
    "low": 263.69,
    "close": 267.32,
    "volume": 6347311
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-09T09:49:06",
    "open": 255.85,
    "high": 260.59,
    "low": 252.41,
    "close": 257.18,
    "volume": 7622022
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-10T09:49:06",
    "open": 265.74,
    "high": 270.91,
    "low": 265.43,
    "close": 266.27,
    "volume": 2105227
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-11T09:49:06",
    "open": 278.93,
    "high": 284.56,
    "low": 274.24,
    "close": 280.63,
    "volume": 6413940
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-12T09:49:06",
    "open": 275.88,
    "high": 282.21,
    "low": 272.17,
    "close": 277.12,
    "volume": 1158761
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-13T09:49:06",
    "open": 269.83,
    "high": 271.54,
    "low": 265.11,
    "close": 270.98,
    "volume": 1457093
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-14T09:49:06",
    "open": 280.04,
    "high": 283.84,
    "low": 277.41,
    "close": 280.96,
    "volume": 9393005
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-15T09:49:06",
    "open": 289.31,
    "high": 291.33,
    "low": 284.01,
    "close": 290.32,
    "volume": 1397939
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-16T09:49:06",
    "open": 280.79,
    "high": 284.34,
    "low": 277.99,
    "close": 279.65,
    "volume": 6425282
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-17T09:49:06",
    "open": 288.95,
    "high": 294.0,
    "low": 286.82,
    "close": 287.59,
    "volume": 5357018
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-18T09:49:06",
    "open": 303.86,
    "high": 306.25,
    "low": 299.63,
    "close": 303.55,
    "volume": 4123283
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-19T09:49:06",
    "open": 299.47,
    "high": 300.79,
    "low": 297.44,
    "close": 300.3,
    "volume": 9764998
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-20T09:49:06",
    "open": 312.12,
    "high": 316.72,
    "low": 306.47,
    "close": 312.54,
    "volume": 8007670
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-21T09:49:06",
    "open": 306.24,
    "high": 311.9,
    "low": 301.37,
    "close": 306.44,
    "volume": 6308206
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-22T09:49:06",
    "open": 316.68,
    "high": 320.13,
    "low": 314.88,
    "close": 317.97,
    "volume": 5975055
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-23T09:49:06",
    "open": 303.5,
    "high": 308.6,
    "low": 300.1,
    "close": 303.21,
    "volume": 5414618
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-24T09:49:06",
    "open": 300.32,
    "high": 302.76,
    "low": 297.99,
    "close": 300.26,
    "volume": 8831631
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-25T09:49:06",
    "open": 304.52,
    "high": 309.55,
    "low": 298.34,
    "close": 304.33,
    "volume": 5557591
  },
  {
    "ticker": "UNH",
    "datetime": "2025-07-26T09:49:06",
    "open": 291.61,
    "high": 297.08,
    "low": 290.13,
    "close": 292.35,
    "volume": 205490
  }
]
